[package]
name = "rcore-user"
version = "0.1.0"
authors = ["Runji Wang <wangrunji0408@163.com>"]
edition = "2018"

[dependencies]
buddy_system_allocator = "0.8"
treebitmap = { git = "https://github.com/jiegec/treebitmap" , features = ["alloc"] }
rlibc = "1.0"
spin = "0.9"
bitflags = "1.2.1"